receivers:
  otlp:
    protocols:
      grpc:
      http:
        cors:
          allowed_origins:
            - http://*
            - https://*

exporters:
  jaeger:
    endpoint: "jaeger-all-in-one:14250"
    tls:
      insecure: true
  zipkin:
    endpoint: "http://zipkin-all-in-one:9411/api/v2/spans"
  logging:
    loglevel: debug
  prometheus:
    endpoint: "0.0.0.0:9464"
  azuremonitor:
    instrumentation_key: <PASTE_INSTRUMENTATION_KEY_HERE>

processors:
  batch:

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [jaeger, zipkin, azuremonitor, logging]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus]
